
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiivxkkmgojxajaohrrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaXZ4a2ttZ29qeGFqYW9ocnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjI1NzgsImV4cCI6MjA2MzA5ODU3OH0.XJjIQxSFwb9GEnaGswfWImuC5WDQN0IeGopjYGPEBEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    }
  }
);

// Admin user details for reference
// Note: This doesn't create an admin user; the SQL migration handles that
export const getAdminCredentials = () => {
  return {
    email: 'admin@agri-consultant.com',
    password: 'Admin123456', // This is a default password that should be changed
    note: 'This admin account was created through SQL migration. For security reasons, please change the password after first login.'
  };
};
