
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiivxkkmgojxajaohrrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaXZ4a2ttZ29qeGFqYW9ocnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjI1NzgsImV4cCI6MjA2MzA5ODU3OH0.XJjIQxSFwb9GEnaGswfWImuC5WDQN0IeGopjYGPEBEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
